pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://mvnrepository.com/artifact" }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter()
        maven { url "https://mvnrepository.com/artifact" }
        maven { url "https://maven.scijava.org/content/repositories/public/" }

    }
}
rootProject.name = "Hesn Islam"
include ':app'
